doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
        types:
            uuid_type: App\SharedContext\Infrastructure\Persistance\Doctrine\Dbal\Types\UuidType
            email_type: App\SharedContext\Infrastructure\Persistance\Doctrine\Dbal\Types\EmailType
            phone_type: App\SharedContext\Infrastructure\Persistance\Doctrine\Dbal\Types\PhoneType
            name_type: App\SharedContext\Infrastructure\Persistance\Doctrine\Dbal\Types\NameType
            attemps_type: App\SharedContext\Infrastructure\Persistance\Doctrine\Dbal\Types\AttempsType
            password_type: App\IdentityAndAccess\Infrastructure\Persistance\Doctrine\Dbal\Types\PasswordType
            otp_password_type: App\OneTimePassword\Infrastructure\Persistance\Doctrine\Dbal\Types\OtpPasswordType
            roles_type: App\IdentityAndAccess\Infrastructure\Persistance\Doctrine\Dbal\Types\RolesType
            magic_link_status_type: App\IdentityAndAccess\Infrastructure\Persistance\Doctrine\Dbal\Types\MagicLinkStatusType
            magic_link_token_type: App\IdentityAndAccess\Infrastructure\Persistance\Doctrine\Dbal\Types\MagicLinkTokenType
            ip_address_type: App\SharedContext\Infrastructure\Persistance\Doctrine\Dbal\Types\IpAddressType
            user_agent_type: App\SharedContext\Infrastructure\Persistance\Doctrine\Dbal\Types\UserAgentType

        profiling_collect_backtrace: "%kernel.debug%"
    orm:
        validate_xml_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App\SharedContext:
                type: xml
                is_bundle: false
                dir: "%kernel.project_dir%/config/doctrine/SharedContext"
                prefix: 'App\SharedContext\Domain'

            App\IdentityAndAccess:
                type: xml
                is_bundle: false
                dir: "%kernel.project_dir%/config/doctrine/IdentityAndAccess"
                prefix: 'App\IdentityAndAccess\Domain'

            App\OneTimePassword:
                type: xml
                is_bundle: false
                dir: "%kernel.project_dir%/config/doctrine/OneTimePassword"
                prefix: 'App\OneTimePassword\Domain'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
