name: Tests

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: read

jobs:
    symfony-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.4"
                  extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
                  coverage: none

            - uses: actions/checkout@v4

            - name: Cache Composer packages
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            - name: Prepare .env.test.local
              run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

            - name: Create Database
              run: |
                  mkdir -p data
                  touch data/database.sqlite

            - name: Generate JWT keys
              run: |
                  mkdir -p config/jwt
                  openssl genrsa -out config/jwt/private.pem -passout pass:testpass 4096
                  openssl rsa -pubout -in config/jwt/private.pem -passin pass:testpass -out config/jwt/public.pem

            - name: Execute tests
              env:
                  APP_ENV: test
                  DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
                  JWT_PASSPHRASE: testpass
                  JWT_SECRET_KEY: "%kernel.project_dir%/config/jwt/private.pem"
                  JWT_PUBLIC_KEY: "%kernel.project_dir%/config/jwt/public.pem"
              run: vendor/bin/phpunit
